"""add credit_cost and credit_package support

Revision ID: daeb47a355de
Revises: 251ad08d9ffc
Create Date: 2026-07-06 11:23:34.127072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'daeb47a355de'
down_revision: Union[str, None] = '251ad08d9ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_CREDIT_COST_BY_MODEL_CODE = {
    "gemini-2.0-flash-lite": 1,
    "deepseek-chat": 1,
    "gpt-4o-mini": 3,
    "claude-3-5-haiku-20241022": 3,
    "gpt-4o": 10,
    "claude-3-5-sonnet-20241022": 10,
    "dall-e-3": 15,
}


def upgrade() -> None:
    op.add_column('model_configs', sa.Column('credit_cost', sa.Integer(), server_default='1', nullable=False))
    op.add_column('payments', sa.Column('credit_package_code', sa.String(length=32), nullable=True))
    op.alter_column('payments', 'tariff_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    model_configs = sa.table(
        "model_configs",
        sa.column("model_code", sa.String),
        sa.column("credit_cost", sa.Integer),
    )
    connection = op.get_bind()
    for model_code, credit_cost in _CREDIT_COST_BY_MODEL_CODE.items():
        connection.execute(
            model_configs.update().where(model_configs.c.model_code == model_code).values(credit_cost=credit_cost)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'tariff_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'credit_package_code')
    op.drop_column('model_configs', 'credit_cost')
    # ### end Alembic commands ###
